# Usamos una imagen base oficial y ligera de Nginx
FROM nginx:alpine

# Copiamos nuestro código fuente a la carpeta pública de Nginx
COPY src/index.html /usr/share/nginx/html/index.html

# Exponemos el puerto 80
EXPOSE 80
